mt6765: disable A/B explicitly
* File "ota_from_target_files.py", line 952, in GenerateAbOtaPackage
AssertionError: META/ab_partitions.txt is required for ab_update.